<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>pacmine</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pacmine.Core\Pacmine.Core.csproj" />
    <ProjectReference Include="..\Pacmine.Environment\Pacmine.Environment.csproj" />
    <ProjectReference Include="..\Pacmine.PackageCraft\Pacmine.PackageCraft.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="3.0.0-preview.4.26230.115" />
    <PackageReference Include="Wcwidth" Version="4.0.1" />
  </ItemGroup>

</Project>
