<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pacmine\Pacmine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Downloader" Version="5.2.0" />
    <PackageReference Include="LuaCSharp" Version="0.5.3" />
  </ItemGroup>

</Project>
